# Generated by Django 3.0.8 on 2020-12-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
