# Generated by Django 3.0.8 on 2020-12-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20201222_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='job_type',
        ),
    ]
